# Generated by Django 6.1 on 2026-09-09 12:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('sobrenome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('criacao_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('mensagem', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('crm', models.CharField(default='', max_length=100)),
                ('especialidade', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
