# Generated by Django 6.1.1 on 2026-09-16 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=30)),
                ('idade', models.IntegerField()),
                ('cpf', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=30)),
                ('idade', models.IntegerField()),
                ('cpf', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(max_length=15)),
                ('turno', models.CharField(max_length=15)),
                ('professor_fk', models.CharField(max_length=15)),
                ('aluno_fk', models.CharField(max_length=15)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True)),
            ],
        ),
    ]
